name: PR checks
on: pull_request

env:
  SECRET_KEY: insecure_test_key
  GREENHOUSE_DATABASE_URL: postgresql://postgres:pw@localhost:5432/postgres
  CANONICAL_DATABASE_URL: postgresql://postgres:pw@localhost:5432/postgres

jobs:
  run-image:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pw
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag hiring.canonical.com .
      - name: Run image
        run: docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key hiring.canonical.com sleep 1 && curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost/check/_status

  run-dotrun:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pw
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install dotrun
        run: |
          sudo snap install dotrun
          sudo chown root:root /

      - name: Install dependencies
        run: /snap/bin/dotrun install

      - name: Build assets
        run: /snap/bin/dotrun build

      - name: Run dotrun
        run: |
          /snap/bin/dotrun &
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8501

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: | 
          python3 -m pip install --upgrade pip
          sudo pip3 install flake8 black

      - name: Lint python
        run: yarn lint-python

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint js
        run: yarn lint-js
